=== GitHubAbhi1406/RestAssured_FakeStore_API_TestAutomation/src/test/resources/SchemaValidation/singleProductSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Generated Schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "price": {
      "type": "number"
    },
    "description": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "image": {
      "type": "string",
      "format": "uri"
    },
    "rating": {
      "type": "object",
      "properties": {
        "rate": {
          "type": "number"
        },
        "count": {
          "type": "integer"
        }
      },
      "required": [
        "rate",
        "count"
      ]
    }
  },
  "required": [
    "id",
    "title",
    "price",
    "description",
    "category",
    "image",
    "rating"
  ]
}

=== GitHubAbhi1406/RestAssured_FakeStore_API_TestAutomation/src/test/resources/PutProduct/putProduct.json
{
    "id": 19,
    "title": "Opna Women's Short Sleeve Moisture",
    "price": 7.95,
    "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
    "category": "women's clothing",
    "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
    "rating": {
        "rate": 4.5,
        "count": 146
    }
}
